### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by Tellev** [enonic/tutorial-myfirstsite#211]
While trying to build the application with `enonic dev` I get an error message saying `Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.`. I have followed the tutorial step by step up until this point.

---
#### Document Details

⚠ *Please do not edit this section. It helps us track and organize our issues.*

* Commit: N/A
* Document: Setting up the developer environment
* Document path: /developer/docs/my-first-site/stable/setup

**Comment by alansemenov** [comment]
@Tellev Thanks for reporting this.

What you see is not an error message but a warning that indicates that gradle config is using features that have to be fixed before migrating to Gradle 9. Just look away from this.

If your build actually failed then there should be another error message in the logs.

**Comment by alansemenov** [comment]
I have now followed the instructions from the tutorial and didn't encounter any build errors.
